clear;
clc;
dim = 4;
order = 3;
x = [-1.0, 0.5, 1.0, -0.5]';

display('Indices of 3th order polynomial generated by "tensor":');
ind_mat1 = tensor(dim, order)

display('Indices of 3th order polynomial generated by "tensor2":');
ind_mat2 = tensor2(dim, order)

display('value of 3th order Legendre polynomial with index by "tensor": ');
eval_tensor_poly(@legendre, x, dim, order, ind_mat1)

display('value of up to 3th order Legendre polynomial with index by "tensor2": ');
ind_mat3 = full_tensor(@tensor2, dim, order);
eval_tensor_poly(@legendre, x, dim, order, ind_mat3)


display('value of derivatives of up to 3th order Legendre polynomial with index by "tensor2": ');
eval_tensor_dpoly(@legendre, @dlegendre, x, dim, order, ind_mat3)
